#!/bin/sh

line=`grep "__version__" setup.py | sed "s/__version__ = //g"`

stripped_line=`echo $line | sed "s/dev//g"`

if [ "$line" != "$stripped_line" ]; then
    # dev
    python setup.py sdist --formats=gztar,zip
else
    # not dev
    python setup.py sdist --formats=gztar,zip register upload
fi


